# Generated by Django 4.2 on 2024-08-30 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Введите название тега.', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(inverse_match=False, message='The field contains invalid characters. Only letters, spaces, and hyphens are allowed.', regex='[^a-zA-Zа-яА-ЯёЁ\\s\\-]')], verbose_name='Название тега'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text='Введите ваше имя.', max_length=150, validators=[django.core.validators.RegexValidator(inverse_match=False, message='The field contains invalid characters. Only letters, spaces, and hyphens are allowed.', regex='[^a-zA-Zа-яА-ЯёЁ\\-]')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(help_text='Введите вашу фамилию.', max_length=150, validators=[django.core.validators.RegexValidator(inverse_match=False, message='The field contains invalid characters. Only letters, spaces, and hyphens are allowed.', regex='[^a-zA-Zа-яА-ЯёЁ\\-]')], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким именем уже существует.'}, help_text='Введите уникальное имя пользователя.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(inverse_match=True, message='The field contains invalid characters. Only letters, spaces, and hyphens are allowed.', regex='[\\$\\%\\^\\&\\#\\:\\;!]')], verbose_name='Имя пользователя'),
        ),
    ]
